-- ============================================================================
-- ScratchBird Compatibility Test Suite
-- Test Category: Sequences - IDENTITY Columns
-- Description: Comprehensive IDENTITY column testing (SQL standard)
-- ============================================================================

-- IDENTITY columns: SQL standard alternative to SERIAL
-- GENERATED ALWAYS: System always generates value
-- GENERATED BY DEFAULT: System generates unless explicitly provided
-- More control than SERIAL, standard SQL syntax

-- Create test database
CREATE DATABASE test_identity_columns_db;
USE test_identity_columns_db;

-- ============================================================================
-- Section 1: GENERATED BY DEFAULT AS IDENTITY
-- ============================================================================

CREATE TABLE test_identity_default (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

-- Auto-generated IDs
INSERT INTO test_identity_default (name) VALUES ('Item 1'), ('Item 2'), ('Item 3');

SELECT id, name FROM test_identity_default ORDER BY id;

-- Can explicitly provide ID
INSERT INTO test_identity_default (id, name) VALUES (100, 'Item 100');

-- Auto-generation continues
INSERT INTO test_identity_default (name) VALUES ('Item 4');

SELECT id, name FROM test_identity_default ORDER BY id;

-- ============================================================================
-- Section 2: GENERATED ALWAYS AS IDENTITY
-- ============================================================================

CREATE TABLE test_identity_always (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

-- Auto-generated IDs
INSERT INTO test_identity_always (name) VALUES ('Item 1'), ('Item 2');

SELECT id, name FROM test_identity_always ORDER BY id;

-- Cannot explicitly provide ID (would fail)
-- INSERT INTO test_identity_always (id, name) VALUES (100, 'Item 100');

-- Can override with OVERRIDING SYSTEM VALUE
INSERT INTO test_identity_always (id, name)
OVERRIDING SYSTEM VALUE
VALUES (100, 'Item 100');

SELECT id, name FROM test_identity_always ORDER BY id;

-- ============================================================================
-- Section 3: IDENTITY with START WITH
-- ============================================================================

CREATE TABLE test_identity_start (
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    code VARCHAR(50)
);

INSERT INTO test_identity_start (code) VALUES ('CODE1'), ('CODE2'), ('CODE3');

SELECT id, code FROM test_identity_start ORDER BY id;

-- ============================================================================
-- Section 4: IDENTITY with INCREMENT BY
-- ============================================================================

CREATE TABLE test_identity_increment (
    id INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 10) PRIMARY KEY,
    value TEXT
);

INSERT INTO test_identity_increment (value) VALUES ('Value 1'), ('Value 2'), ('Value 3');

SELECT id, value FROM test_identity_increment ORDER BY id;

-- ============================================================================
-- Section 5: IDENTITY with Multiple Options
-- ============================================================================

CREATE TABLE test_identity_options (
    id INT GENERATED BY DEFAULT AS IDENTITY (
        START WITH 100
        INCREMENT BY 5
        MINVALUE 100
        MAXVALUE 200
        CYCLE
        CACHE 10
    ) PRIMARY KEY,
    data TEXT
);

INSERT INTO test_identity_options (data)
SELECT 'Data ' || i FROM generate_series(1, 25) i;

SELECT id, data FROM test_identity_options ORDER BY id;

-- ============================================================================
-- Section 6: BIGINT IDENTITY
-- ============================================================================

CREATE TABLE test_identity_bigint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT
);

INSERT INTO test_identity_bigint (description) VALUES ('Desc 1'), ('Desc 2');

SELECT id, description FROM test_identity_bigint ORDER BY id;

-- Verify column type
SELECT column_name, data_type, identity_generation
FROM information_schema.columns
WHERE table_name = 'test_identity_bigint' AND column_name = 'id';

-- ============================================================================
-- Section 7: IDENTITY vs SERIAL Comparison
-- ============================================================================

-- SERIAL approach
CREATE TABLE test_compare_serial (
    id SERIAL PRIMARY KEY,
    value TEXT
);

-- IDENTITY approach (equivalent)
CREATE TABLE test_compare_identity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

INSERT INTO test_compare_serial (value) VALUES ('Serial 1'), ('Serial 2');
INSERT INTO test_compare_identity (value) VALUES ('Identity 1'), ('Identity 2');

-- Both work similarly
SELECT id, value FROM test_compare_serial ORDER BY id;
SELECT id, value FROM test_compare_identity ORDER BY id;

-- IDENTITY is SQL standard, SERIAL is PostgreSQL-specific

-- ============================================================================
-- Section 8: Querying IDENTITY Column Information
-- ============================================================================

SELECT
    table_name,
    column_name,
    data_type,
    identity_generation,
    identity_start,
    identity_increment,
    identity_maximum,
    identity_minimum,
    identity_cycle
FROM information_schema.columns
WHERE table_name = 'test_identity_options'
  AND column_name = 'id';

-- ============================================================================
-- Section 9: ALTER TABLE with IDENTITY
-- ============================================================================

CREATE TABLE test_alter_identity (
    id INT PRIMARY KEY,
    name VARCHAR(200)
);

-- Add IDENTITY to existing column
ALTER TABLE test_alter_identity
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO test_alter_identity (name) VALUES ('Item 1'), ('Item 2');

SELECT id, name FROM test_alter_identity ORDER BY id;

-- Change IDENTITY options
ALTER TABLE test_alter_identity
    ALTER COLUMN id SET GENERATED ALWAYS;

-- Now cannot provide explicit values
-- INSERT INTO test_alter_identity (id, name) VALUES (100, 'Item 100');  -- Fails

-- ============================================================================
-- Section 10: Dropping IDENTITY
-- ============================================================================

CREATE TABLE test_drop_identity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

INSERT INTO test_drop_identity (value) VALUES ('Value 1'), ('Value 2');

-- Remove IDENTITY
ALTER TABLE test_drop_identity
    ALTER COLUMN id DROP IDENTITY;

-- Now must provide IDs manually
INSERT INTO test_drop_identity (id, value) VALUES (100, 'Value 100');

SELECT id, value FROM test_drop_identity ORDER BY id;

-- ============================================================================
-- Section 11: IDENTITY with RESTART
-- ============================================================================

CREATE TABLE test_identity_restart (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data TEXT
);

INSERT INTO test_identity_restart (data) VALUES ('Data 1'), ('Data 2'), ('Data 3');

-- Restart sequence
ALTER TABLE test_identity_restart
    ALTER COLUMN id RESTART;

INSERT INTO test_identity_restart (data) VALUES ('Data 4');

SELECT id, data FROM test_identity_restart ORDER BY id;

-- Restart with specific value
ALTER TABLE test_identity_restart
    ALTER COLUMN id RESTART WITH 100;

INSERT INTO test_identity_restart (data) VALUES ('Data 5');

SELECT id, data FROM test_identity_restart ORDER BY id;

-- ============================================================================
-- Section 12: IDENTITY Sequence Queries
-- ============================================================================

CREATE TABLE test_identity_sequence (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

-- Get underlying sequence name
SELECT pg_get_serial_sequence('test_identity_sequence', 'id') AS sequence_name;

-- Query sequence directly
SELECT
    last_value,
    start_value,
    increment_by
FROM pg_sequences
WHERE sequencename = (
    SELECT pg_get_serial_sequence('test_identity_sequence', 'id')::regclass::text
);

-- ============================================================================
-- Section 13: Multiple IDENTITY Columns (Not Allowed)
-- ============================================================================

-- Only one IDENTITY column per table is allowed
CREATE TABLE test_single_identity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_num INT,  -- Cannot be IDENTITY if id already is
    name VARCHAR(200)
);

-- Would fail: only one identity column allowed
-- ALTER TABLE test_single_identity
--     ALTER COLUMN order_num ADD GENERATED BY DEFAULT AS IDENTITY;

-- ============================================================================
-- Section 14: IDENTITY with INSERT...RETURNING
-- ============================================================================

CREATE TABLE test_identity_returning (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Return generated IDENTITY value
INSERT INTO test_identity_returning (name)
VALUES ('Item 1')
RETURNING id, name, created_at;

-- Bulk insert with RETURNING
INSERT INTO test_identity_returning (name)
VALUES ('Item 2'), ('Item 3'), ('Item 4')
RETURNING id, name;

-- ============================================================================
-- Section 15: IDENTITY with COPY
-- ============================================================================

CREATE TABLE test_identity_copy (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

-- COPY can override IDENTITY
-- Create temp file for COPY
CREATE TEMP TABLE temp_identity_data (id INT, value TEXT);
INSERT INTO temp_identity_data VALUES (100, 'Value 100'), (101, 'Value 101');

-- Insert from temp table
INSERT INTO test_identity_copy (id, value)
SELECT id, value FROM temp_identity_data;

-- Continue with auto-generation
INSERT INTO test_identity_copy (value) VALUES ('Value 1');

SELECT id, value FROM test_identity_copy ORDER BY id;

-- ============================================================================
-- Section 16: IDENTITY Cycle Behavior
-- ============================================================================

CREATE TABLE test_identity_cycle (
    id INT GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1
        INCREMENT BY 1
        MINVALUE 1
        MAXVALUE 5
        CYCLE
    ) PRIMARY KEY,
    data TEXT
);

-- Insert values that cycle
INSERT INTO test_identity_cycle (data)
SELECT 'Data ' || i FROM generate_series(1, 12) i;

-- IDs cycle: 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2
-- Note: PRIMARY KEY constraint will prevent duplicate keys
-- In practice, CYCLE is rarely used with PKs

-- ============================================================================
-- Section 17: IDENTITY with ON CONFLICT
-- ============================================================================

CREATE TABLE test_identity_conflict (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) UNIQUE,
    value TEXT
);

INSERT INTO test_identity_conflict (code, value) VALUES ('CODE1', 'Value 1');

-- Upsert
INSERT INTO test_identity_conflict (code, value)
VALUES ('CODE1', 'Updated Value')
ON CONFLICT (code) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO test_identity_conflict (code, value) VALUES ('CODE2', 'Value 2');

SELECT id, code, value FROM test_identity_conflict ORDER BY id;

-- ============================================================================
-- Section 18: IDENTITY in Partitioned Tables
-- ============================================================================

CREATE TABLE test_identity_partitioned (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(50),
    data TEXT,
    PRIMARY KEY (id, category)
) PARTITION BY LIST (category);

CREATE TABLE test_part_a PARTITION OF test_identity_partitioned
    FOR VALUES IN ('A');

CREATE TABLE test_part_b PARTITION OF test_identity_partitioned
    FOR VALUES IN ('B');

-- IDENTITY sequence shared across partitions
INSERT INTO test_identity_partitioned (category, data) VALUES
    ('A', 'Data A1'),
    ('B', 'Data B1'),
    ('A', 'Data A2');

SELECT id, category, data FROM test_identity_partitioned ORDER BY id;

-- ============================================================================
-- Section 19: Setting IDENTITY Value
-- ============================================================================

CREATE TABLE test_identity_setval (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT
);

INSERT INTO test_identity_setval (value) VALUES ('Value 1'), ('Value 2');

-- Get sequence name
DO $$
DECLARE
    seq_name TEXT;
BEGIN
    seq_name := pg_get_serial_sequence('test_identity_setval', 'id');
    -- Set sequence value
    PERFORM setval(seq_name, 100);
END $$;

-- Next insert uses updated sequence
INSERT INTO test_identity_setval (value) VALUES ('Value 3');

SELECT id, value FROM test_identity_setval ORDER BY id;

-- ============================================================================
-- Section 20: Best Practices
-- ============================================================================

CREATE TABLE test_identity_best_practices (
    id INT PRIMARY KEY,
    guideline TEXT
);

INSERT INTO test_identity_best_practices VALUES
    (1, 'IDENTITY is SQL standard, prefer over SERIAL for portability'),
    (2, 'GENERATED ALWAYS prevents manual ID assignment'),
    (3, 'GENERATED BY DEFAULT allows manual IDs when needed'),
    (4, 'Use OVERRIDING SYSTEM VALUE to bypass ALWAYS restriction'),
    (5, 'Only one IDENTITY column allowed per table'),
    (6, 'IDENTITY creates underlying sequence automatically'),
    (7, 'Use START WITH to set initial value'),
    (8, 'INCREMENT BY for non-standard increments'),
    (9, 'CYCLE carefully - usually inappropriate for PKs'),
    (10, 'Use BIGINT IDENTITY for high-volume tables'),
    (11, 'RESTART to reset sequence without recreating table'),
    (12, 'Query information_schema.columns for IDENTITY metadata'),
    (13, 'IDENTITY preferred in new applications (standard SQL)'),
    (14, 'Use INSERT...RETURNING to get generated values'),
    (15, 'ALTER TABLE to add/modify/remove IDENTITY on existing columns');

SELECT id, guideline FROM test_identity_best_practices ORDER BY id;

-- ============================================================================
-- Cleanup
-- ============================================================================

DROP TABLE test_identity_best_practices;
DROP TABLE test_identity_setval;
DROP TABLE test_part_b;
DROP TABLE test_part_a;
DROP TABLE test_identity_partitioned;
DROP TABLE test_identity_conflict;
DROP TABLE test_identity_cycle;
DROP TABLE temp_identity_data;
DROP TABLE test_identity_copy;
DROP TABLE test_identity_returning;
DROP TABLE test_single_identity;
DROP TABLE test_identity_sequence;
DROP TABLE test_identity_restart;
DROP TABLE test_drop_identity;
DROP TABLE test_alter_identity;
DROP TABLE test_compare_identity;
DROP TABLE test_compare_serial;
DROP TABLE test_identity_bigint;
DROP TABLE test_identity_options;
DROP TABLE test_identity_increment;
DROP TABLE test_identity_start;
DROP TABLE test_identity_always;
DROP TABLE test_identity_default;

DROP DATABASE test_identity_columns_db;

-- End of IDENTITY column tests
