#include "scratchbird/sblr/v3_opcode_identity.h"

#include <string>
#include <string_view>
#include <unordered_map>

#include "scratchbird/sblr/v3_canonical_feature_map.generated.h"
#include "scratchbird/sblr/v3_opcode_registry.h"

namespace scratchbird::sblr::v3 {

namespace {

static const std::unordered_map<std::string_view, std::string_view> kExactSymbolMap = {
    {"SBLR3_VERSION", "OP_MOD_BEGIN"},
    {"SBLR3_END", "OP_MOD_END"},
    {"SBLR3_EXTENDED_OPCODE", "OP_MOD_FEATURE"},

    {"SBLR3_START_TRANSACTION", "OP_STMT_TXN_BEGIN"},
    {"SBLR3_COMMIT", "OP_STMT_TXN_COMMIT"},
    {"SBLR3_ROLLBACK", "OP_STMT_TXN_ROLLBACK"},
    {"SBLR3_SAVEPOINT", "OP_STMT_TXN_SAVEPOINT"},

    {"SBLR3_SELECT", "OP_STMT_DML_SELECT"},
    {"SBLR3_INSERT", "OP_STMT_DML_INSERT"},
    {"SBLR3_UPDATE", "OP_STMT_DML_UPDATE"},
    {"SBLR3_DELETE", "OP_STMT_DML_DELETE"},
    {"SBLR3_MERGE_START", "OP_STMT_DML_MERGE"},

    {"SBLR3_CREATE_TABLE", "OP_STMT_DDL_CREATE_TABLE"},
    {"SBLR3_CREATE_SCHEMA", "OP_STMT_DDL_CREATE_SCHEMA"},
    {"SBLR3_CREATE_DATABASE", "OP_STMT_DDL_CREATE_DATABASE_NATIVE"},
    {"SBLR3_CREATE_DATABASE_EMULATED", "OP_STMT_DDL_CREATE_DATABASE_EMULATED"},
    {"SBLR3_ALTER_TABLE", "OP_STMT_DDL_ALTER_TABLE"},
    {"SBLR3_DROP_TABLE", "OP_STMT_DDL_DROP_TABLE"},
    {"SBLR3_CREATE_VIEW", "OP_STMT_DDL_CREATE_VIEW"},
    {"SBLR3_CREATE_TABLE_AS", "OP_STMT_DDL_CREATE_MATERIALIZED_VIEW"},
    {"SBLR3_REFRESH_MATERIALIZED_VIEW", "OP_STMT_DDL_REFRESH_MATERIALIZED_VIEW"},
    {"SBLR3_CREATE_INDEX", "OP_STMT_DDL_CREATE_INDEX"},
    {"SBLR3_ALTER_INDEX", "OP_STMT_DDL_ALTER_INDEX"},
    {"SBLR3_DROP_INDEX", "OP_STMT_DDL_DROP_INDEX"},
    {"SBLR3_CREATE_SEQUENCE", "OP_STMT_DDL_CREATE_SEQUENCE"},
    {"SBLR3_CREATE_DOMAIN", "OP_STMT_DDL_CREATE_DOMAIN"},
    {"SBLR3_CREATE_DOMAIN_RECORD", "OP_STMT_DDL_CREATE_DOMAIN_RECORD"},
    {"SBLR3_CREATE_DOMAIN_ENUM", "OP_STMT_DDL_CREATE_DOMAIN_ENUM"},
    {"SBLR3_CREATE_DOMAIN_SET", "OP_STMT_DDL_CREATE_DOMAIN_SET"},
    {"SBLR3_CREATE_DOMAIN_RANGE", "OP_STMT_DDL_CREATE_DOMAIN_RANGE"},
    {"SBLR3_ALTER_DOMAIN", "OP_STMT_DDL_ALTER_DOMAIN"},
    {"SBLR3_CREATE_TYPE", "OP_STMT_DDL_CREATE_TYPE"},
    {"SBLR3_CREATE_FUNCTION_STMT", "OP_STMT_DDL_CREATE_FUNCTION"},
    {"SBLR3_CREATE_PROCEDURE_STMT", "OP_STMT_DDL_CREATE_PROCEDURE"},
    {"SBLR3_CREATE_PACKAGE_STMT", "OP_STMT_DDL_CREATE_PACKAGE"},
    {"SBLR3_CREATE_TRIGGER", "OP_STMT_DDL_CREATE_TRIGGER"},
    {"SBLR3_CREATE_DB_TRIGGER", "OP_STMT_DDL_CREATE_EVENT"},
    {"SBLR3_CREATE_POLICY", "OP_STMT_DDL_CREATE_POLICY"},
    {"SBLR3_GRANT", "OP_STMT_DDL_GRANT"},
    {"SBLR3_REVOKE", "OP_STMT_DDL_REVOKE"},

    {"SBLR3_TEXTSEARCH_CREATE_DICTIONARY", "OP_STMT_TEXTSEARCH_CREATE_DICTIONARY"},
    {"SBLR3_TEXTSEARCH_ALTER_DICTIONARY", "OP_STMT_TEXTSEARCH_ALTER_DICTIONARY"},
    {"SBLR3_TEXTSEARCH_DROP_DICTIONARY", "OP_STMT_TEXTSEARCH_DROP_DICTIONARY"},
    {"SBLR3_TEXTSEARCH_CREATE_CONFIGURATION", "OP_STMT_TEXTSEARCH_CREATE_CONFIGURATION"},
    {"SBLR3_TEXTSEARCH_ALTER_CONFIGURATION", "OP_STMT_TEXTSEARCH_ALTER_CONFIGURATION"},
    {"SBLR3_TEXTSEARCH_DROP_CONFIGURATION", "OP_STMT_TEXTSEARCH_DROP_CONFIGURATION"},
    {"SBLR3_TEXTSEARCH_LOAD_DICTIONARY_DATA", "OP_STMT_TEXTSEARCH_LOAD_DICTIONARY_DATA"},

    {"SBLR3_COPY", "OP_STMT_DML_COPY_BULK"},
    {"SBLR3_RETURNING", "OP_STMT_DML_RETURNING"},

    {"SBLR3_PREPARE_STMT", "OP_STMT_PREPARE_STATEMENT"},
    {"SBLR3_EXECUTE_PREPARED", "OP_STMT_EXECUTE_PREPARED"},
    {"SBLR3_DEALLOCATE_PREPARED", "OP_STMT_DEALLOCATE_PREPARED"},

    {"SBLR3_CREATE_FOREIGN_DATA_WRAPPER", "OP_STMT_FDW_CREATE_WRAPPER"},
    {"SBLR3_CREATE_FOREIGN_SERVER", "OP_STMT_FDW_CREATE_SERVER"},
    {"SBLR3_CREATE_USER_MAPPING", "OP_STMT_FDW_USER_MAPPING"},
    {"SBLR3_CREATE_FOREIGN_TABLE", "OP_STMT_FDW_FOREIGN_TABLE"},

    {"SBLR3_ANALYZE", "OP_STMT_ADMIN_ANALYZE"},
    {"SBLR3_SWEEP", "OP_STMT_ADMIN_SWEEP"},
    {"SBLR3_ADMIN_BACKUP", "OP_STMT_ADMIN_BACKUP"},
    {"SBLR3_ADMIN_RESTORE", "OP_STMT_ADMIN_RESTORE"},
    {"SBLR3_ADMIN_VALIDATE", "OP_STMT_ADMIN_VALIDATE"},

    {"SBLR3_SET_VARIABLE", "OP_STMT_SESSION_SET"},
    {"SBLR3_SHOW_VARIABLE", "OP_STMT_SESSION_SHOW"},
    {"SBLR3_SHOW_SYSTEM", "OP_STMT_SHOW_SYSTEM_OBJECTS"},
    {"SBLR3_SHOW_ALL", "OP_STMT_CONFIG_SHOW"},
    {"SBLR3_ALTER_SYSTEM", "OP_STMT_CONFIG_SET"},
    {"SBLR3_SESSION_RESET", "OP_STMT_SESSION_RESET"},
    {"SBLR3_CONFIG_RESET", "OP_STMT_CONFIG_RESET"},
    {"SBLR3_CONFIG_HISTORY", "OP_STMT_CONFIG_HISTORY"},
    {"SBLR3_CONFIG_RELOAD", "OP_STMT_CONFIG_RELOAD"},
    {"SBLR3_CONFIG_RESOURCE_BUNDLES_SHOW", "OP_STMT_CONFIG_RESOURCE_BUNDLES_SHOW"},
    {"SBLR3_CONFIG_RESOURCE_BUNDLE_VALIDATE", "OP_STMT_CONFIG_RESOURCE_BUNDLE_VALIDATE"},
    {"SBLR3_CONFIG_RESOURCE_BUNDLE_ACTIVATE", "OP_STMT_CONFIG_RESOURCE_BUNDLE_ACTIVATE"},

    {"SBLR3_EXECUTE_JOB", "OP_STMT_JOB_SUBMIT"},
    {"SBLR3_CREATE_JOB", "OP_STMT_JOB_SCHEDULE"},
    {"SBLR3_CANCEL_JOB_RUN", "OP_STMT_JOB_CANCEL"},
    {"SBLR3_ALTER_JOB", "OP_STMT_JOB_RETRY"},
    {"SBLR3_SHOW_JOB", "OP_STMT_JOB_SHOW"},

    {"SBLR3_SHOW_INDEX", "OP_STMT_IDX_SHOW_OPTIONS"},
    {"SBLR3_SHOW_INDEXES", "OP_STMT_IDX_SHOW_USAGE"},
    {"SBLR3_INDEX_REINDEX", "OP_STMT_IDX_REBUILD"},
    {"SBLR3_INDEX_VACUUM", "OP_STMT_IDX_REBALANCE"},
    {"SBLR3_INDEX_STATS", "OP_STMT_IDX_ANALYZE"},
    {"SBLR3_INDEX_SEARCH", "OP_STMT_IDX_LIGHT_SCAN"},
    {"SBLR3_INDEX_SCAN", "OP_STMT_IDX_DIAGNOSTIC_SCAN"},
    {"SBLR3_INDEX_TYPE", "OP_STMT_IDX_SHOW_STORAGE"},
    {"SBLR3_IDX_SET_OPTIONS", "OP_STMT_IDX_SET_OPTIONS"},
    {"SBLR3_IDX_RESET_OPTIONS", "OP_STMT_IDX_RESET_OPTIONS"},
    {"SBLR3_IDX_RELOCATE", "OP_STMT_IDX_RELOCATE"},
    {"SBLR3_IDX_DEFAULTS_SET", "OP_STMT_IDX_DEFAULTS_SET"},
    {"SBLR3_IDX_DEFAULTS_RESET", "OP_STMT_IDX_DEFAULTS_RESET"},
    {"SBLR3_IDX_SHOW_HEALTH", "OP_STMT_IDX_SHOW_HEALTH"},
    {"SBLR3_IDX_SHOW_CONTENTION", "OP_STMT_IDX_SHOW_CONTENTION"},

    {"SBLR3_CQL_KEYSPACE", "OP_STMT_CQL_KEYSPACE"},
    {"SBLR3_CQL_BATCH", "OP_STMT_CQL_BATCH"},
    {"SBLR3_CQL_TTL", "OP_STMT_CQL_TTL"},
    {"SBLR3_CQL_WRITETIME", "OP_STMT_CQL_WRITETIME"},
    {"SBLR3_MONGO_FIND", "OP_STMT_MONGO_FIND"},
    {"SBLR3_MONGO_AGGREGATE", "OP_STMT_MONGO_AGGREGATE"},
    {"SBLR3_MONGO_FIND_AND_MODIFY", "OP_STMT_MONGO_FIND_AND_MODIFY"},
    {"SBLR3_MONGO_BULK_WRITE", "OP_STMT_MONGO_BULK_WRITE"},
    {"SBLR3_CYPHER_MATCH", "OP_STMT_CYPHER_MATCH"},
    {"SBLR3_CYPHER_MERGE", "OP_STMT_CYPHER_MERGE"},
    {"SBLR3_CYPHER_UNWIND", "OP_STMT_CYPHER_UNWIND"},
    {"SBLR3_CYPHER_CALL", "OP_STMT_CYPHER_CALL"},
    {"SBLR3_REDIS_STRING", "OP_STMT_REDIS_STRING"},
    {"SBLR3_REDIS_HASH", "OP_STMT_REDIS_HASH"},
    {"SBLR3_REDIS_LIST", "OP_STMT_REDIS_LIST"},
    {"SBLR3_REDIS_SET", "OP_STMT_REDIS_SET"},
    {"SBLR3_REDIS_ZSET", "OP_STMT_REDIS_ZSET"},
    {"SBLR3_REDIS_STREAM", "OP_STMT_REDIS_STREAM"},
    {"SBLR3_REDIS_PUBSUB", "OP_STMT_REDIS_PUBSUB"},
    {"SBLR3_MILVUS_CREATE_COLLECTION", "OP_STMT_MILVUS_CREATE_COLLECTION"},
    {"SBLR3_MILVUS_DROP_COLLECTION", "OP_STMT_MILVUS_DROP_COLLECTION"},
    {"SBLR3_MILVUS_CREATE_INDEX", "OP_STMT_MILVUS_CREATE_INDEX"},
    {"SBLR3_MILVUS_DROP_INDEX", "OP_STMT_MILVUS_DROP_INDEX"},
    {"SBLR3_MILVUS_INSERT", "OP_STMT_MILVUS_INSERT"},
    {"SBLR3_MILVUS_DELETE", "OP_STMT_MILVUS_DELETE"},
    {"SBLR3_MILVUS_SEARCH", "OP_STMT_MILVUS_SEARCH"},
    {"SBLR3_MILVUS_QUERY", "OP_STMT_MILVUS_QUERY"},
    {"SBLR3_CLUSTER_WORKLOAD_CLASS", "OP_STMT_CLUSTER_WORKLOAD_CLASS"},
    {"SBLR3_CLUSTER_WORKLOAD_ROUTE", "OP_STMT_CLUSTER_WORKLOAD_ROUTE"},
    {"SBLR3_CLUSTER_ADMISSION_POLICY", "OP_STMT_CLUSTER_ADMISSION_POLICY"},
    {"SBLR3_CLUSTER_ADMISSION_BINDING", "OP_STMT_CLUSTER_ADMISSION_BINDING"},
    {"SBLR3_CLUSTER_SET_STATE", "OP_STMT_CLUSTER_SET_STATE"},
    {"SBLR3_CLUSTER_SHOW_STATE", "OP_STMT_CLUSTER_SHOW_STATE"},
    {"SBLR3_CLUSTER_SHOW_ROUTING_PLAN", "OP_STMT_CLUSTER_SHOW_ROUTING_PLAN"},
    {"SBLR3_CLUSTER_SHOW_ADMISSION_STATUS", "OP_STMT_CLUSTER_SHOW_ADMISSION_STATUS"},
    {"SBLR3_ALERT_RULE_DDL", "OP_STMT_ALERT_RULE_DDL"},
    {"SBLR3_ALERT_TARGET_DDL", "OP_STMT_ALERT_TARGET_DDL"},
    {"SBLR3_ALERT_ROUTE_DDL", "OP_STMT_ALERT_ROUTE_DDL"},
    {"SBLR3_ALERT_SILENCE_DDL", "OP_STMT_ALERT_SILENCE_DDL"},
    {"SBLR3_ALERT_ACK", "OP_STMT_ALERT_ACK"},
    {"SBLR3_ALERT_SHOW", "OP_STMT_ALERT_SHOW"},
    {"SBLR3_HEALING_POLICY_DDL", "OP_STMT_HEALING_POLICY_DDL"},
    {"SBLR3_HEALING_ACTION_DDL", "OP_STMT_HEALING_ACTION_DDL"},
    {"SBLR3_HEALING_RUN", "OP_STMT_HEALING_RUN"},
    {"SBLR3_HEALING_SHOW_RUNS", "OP_STMT_HEALING_SHOW_RUNS"},
    {"SBLR3_JOB_TYPE_DDL", "OP_STMT_JOB_TYPE_DDL"},
    {"SBLR3_JOB_TYPE_PARAM_SET", "OP_STMT_JOB_TYPE_PARAM_SET"},
    {"SBLR3_SHARD_POLICY_DDL", "OP_STMT_SHARD_POLICY_DDL"},
    {"SBLR3_SHARD_DDL", "OP_STMT_SHARD_DDL"},
    {"SBLR3_SHARD_REPLICA_DDL", "OP_STMT_SHARD_REPLICA_DDL"},
    {"SBLR3_SHARD_MIGRATE", "OP_STMT_SHARD_MIGRATE"},
    {"SBLR3_SHARD_SHOW", "OP_STMT_SHARD_SHOW"},
    {"SBLR3_CUBE_DDL", "OP_STMT_CUBE_DDL"},
    {"SBLR3_CUBE_REFRESH", "OP_STMT_CUBE_REFRESH"},
    {"SBLR3_CUBE_SHOW_STATS", "OP_STMT_CUBE_SHOW_STATS"},
    {"SBLR3_SECURITY_ENCRYPTION_PROFILE", "OP_STMT_SECURITY_ENCRYPTION_PROFILE"},
    {"SBLR3_SECURITY_ENCRYPTION_KEY", "OP_STMT_SECURITY_ENCRYPTION_KEY"},
    {"SBLR3_SECURITY_KEY_SHARD_SUBMIT", "OP_STMT_SECURITY_KEY_SHARD_SUBMIT"},
    {"SBLR3_SECURITY_UNLOCK_DATABASE", "OP_STMT_SECURITY_UNLOCK_DATABASE"},
    {"SBLR3_SECURITY_CERT_DDL", "OP_STMT_SECURITY_CERT_DDL"},
    {"SBLR3_SECURITY_PRIVATE_KEY_ROTATE", "OP_STMT_SECURITY_PRIVATE_KEY_ROTATE"},
    {"SBLR3_SECURITY_SHOW_STATUS", "OP_STMT_SECURITY_SHOW_STATUS"},
    {"SBLR3_SERVICE_CHANNEL_BACKUP", "OP_STMT_SERVICE_CHANNEL_BACKUP"},
    {"SBLR3_SERVICE_CHANNEL_EVENTS", "OP_STMT_SERVICE_CHANNEL_EVENTS"},
    {"SBLR3_SERVICE_CHANNEL_PROGRESS", "OP_STMT_SERVICE_CHANNEL_PROGRESS"},

    {"SBLR3_PSQL_POST_EVENT", "OP_STMT_NOTIFY_PUBLISH"},
    {"SBLR3_CONNECT", "OP_STMT_NOTIFY_SUBSCRIBE"},
    {"SBLR3_DISCONNECT", "OP_STMT_NOTIFY_UNSUBSCRIBE"},
};

std::string normalizeExprSuffix(std::string_view suffix) {
    if (suffix == "SUBTRACT") return "SUB";
    if (suffix == "MULTIPLY") return "MUL";
    if (suffix == "DIVIDE") return "DIV";
    if (suffix == "MODULO") return "MOD";
    if (suffix == "NE") return "NEQ";
    if (suffix == "LE") return "LTE";
    if (suffix == "GE") return "GTE";
    return std::string(suffix);
}

std::string mapByPrefix(std::string_view v3_name) {
    constexpr std::string_view kPrefix = "SBLR3_";
    if (v3_name.rfind(kPrefix, 0) != 0) {
        return std::string("OP_COMPAT_") + std::string(v3_name);
    }

    std::string_view suffix = v3_name.substr(kPrefix.size());
    if (suffix.rfind("TYPE_", 0) == 0) {
        return std::string("OP_TYPE_") + std::string(suffix.substr(5));
    }
    if (suffix.rfind("LITERAL_", 0) == 0) {
        return std::string("OP_VAL_") + std::string(suffix.substr(8));
    }
    if (suffix.rfind("EXPR_", 0) == 0) {
        return std::string("OP_EXPR_") + normalizeExprSuffix(suffix.substr(5));
    }
    if (suffix.rfind("PSQL_", 0) == 0) {
        return std::string("OP_FLOW_PSQL_") + std::string(suffix.substr(5));
    }
    if (suffix.rfind("CURSOR_", 0) == 0) {
        return std::string("OP_FLOW_CURSOR_") + std::string(suffix.substr(7));
    }
    if (suffix.rfind("FUNC_", 0) == 0) {
        return std::string("OP_EXPR_FUNC_") + std::string(suffix.substr(5));
    }
    if (suffix.rfind("AGG_", 0) == 0) {
        return std::string("OP_EXPR_AGG_") + std::string(suffix.substr(4));
    }
    if (suffix.rfind("WIN_", 0) == 0) {
        return std::string("OP_EXPR_WIN_") + std::string(suffix.substr(4));
    }
    return std::string("OP_COMPAT_") + std::string(suffix);
}

}  // namespace

std::string canonicalOpcodeSymbolForV3Name(std::string_view v3_name) {
    if (auto it = kExactSymbolMap.find(v3_name); it != kExactSymbolMap.end()) {
        return std::string(it->second);
    }
    return mapByPrefix(v3_name);
}

std::string canonicalOpcodeSymbolForOpcode(uint16_t opcode) {
    const char* name = opcodeName(opcode);
    if (name == nullptr) {
        return "OP_UNKNOWN";
    }
    return canonicalOpcodeSymbolForV3Name(name);
}

bool opcodeMapsToCanonicalFeatureName(std::string_view v3_name) {
    const std::string canonical_symbol = canonicalOpcodeSymbolForV3Name(v3_name);
    return isCanonicalFeatureOpcodeSymbol(canonical_symbol);
}

bool opcodeMapsToCanonicalFeature(uint16_t opcode) {
    const char* name = opcodeName(opcode);
    if (name == nullptr) {
        return false;
    }
    return opcodeMapsToCanonicalFeatureName(name);
}

}  // namespace scratchbird::sblr::v3
