#include "scratchbird/engine/parser_ddl.h"

#include <cassert>

using namespace scratchbird::engine;

int main()
{
    // CREATE TABLE capture of column/constraints/raw attrs
    {
        auto ast =
            parse_ddl_table("CREATE TABLE t (id INT NOT NULL, CONSTRAINT pk PRIMARY KEY(id))");
        assert(ast.kind == NodeKind::DdlTable);
        assert(ast.ddlTable.name == "t");
        assert(!ast.ddlTable.columns_raw.empty());
    }
    // CREATE TABLE split columns vs constraints and identity/computed presence
    {
        auto ast = parse_ddl_table("CREATE TABLE t( id INT GENERATED BY DEFAULT AS IDENTITY, a "
                                   "INT, CONSTRAINT pk PRIMARY KEY(id), CHECK (a > 0) )");
        assert(ast.kind == NodeKind::DdlTable);
        assert(ast.ddlTable.name == "t");
        assert(!ast.ddlTable.column_defs_raw.empty());
        assert(!ast.ddlTable.constraints_raw.empty());
    }
    // ALTER TABLE minimal capture and TYPE change diagnostic
    {
        auto ast = parse_ddl_table("ALTER TABLE t ALTER COLUMN a TYPE ");
        bool saw = false;
        for (auto& w : ast.warnings)
            if (w.find("TYPE missing type") != std::string::npos)
                saw = true;
        assert(saw);
    }
    return 0;
}
