SHOW SEARCH_PATH;

SET SEARCH_PATH TO 'public';
SHOW SEARCH_PATH;

SET STATEMENT_TIMEOUT = '2s';
SHOW STATEMENT_TIMEOUT;

BEGIN;
SET LOCAL statement_timeout = '500ms';
SHOW STATEMENT_TIMEOUT;
COMMIT;
SHOW STATEMENT_TIMEOUT;

SET TIME ZONE 'UTC';
SHOW TIME ZONE;
SET TIME ZONE DEFAULT;
SHOW TIME ZONE;

SHOW ALL;

ALTER SYSTEM SET scheduler.enabled = false;
ALTER SYSTEM SET scheduler.enabled = true;
