SHOW CURRENT_SCHEMA;
SHOW CURRENT_ROLE;
SHOW CURRENT_USER;
SHOW TRANSACTION ISOLATION LEVEL;

SET SQL DIALECT 3;
SHOW SQL DIALECT;
SET NAMES UTF8;
SHOW CHARSET;

SET AUTOCOMMIT ON;
SHOW AUTOCOMMIT;
SET AUTOCOMMIT OFF;
SHOW AUTOCOMMIT;

SET TIME ZONE 'America/New_York';
SHOW TIME ZONE;
SET TIME ZONE '+02:00';
SHOW TIME ZONE;
RESET TIME ZONE;
SHOW TIME ZONE;

SET SEARCH_PATH TO 'public', 'sys';
SHOW SEARCH_PATH;
RESET SEARCH_PATH;
SHOW SEARCH_PATH;

SET LOCAL statement_timeout = '1s';
SHOW STATEMENT_TIMEOUT;
SET LOCAL statement_timeout = DEFAULT;
SHOW STATEMENT_TIMEOUT;

SET ROLE NONE;
SHOW CURRENT_ROLE;
RESET ROLE;
SHOW CURRENT_ROLE;

SET SESSION AUTHORIZATION DEFAULT;

SHOW ALL;
SHOW VERSION;
SHOW DATABASE;
SHOW SYSTEM;
SHOW METRICS;
