RECREATE TABLE VW_JOIN_SCAN_A (
  ID INTEGER NOT NULL PRIMARY KEY,
  GRP INTEGER NOT NULL,
  PAYLOAD VARCHAR(32)
);
RECREATE TABLE VW_JOIN_SCAN_B (
  ID INTEGER NOT NULL PRIMARY KEY,
  A_ID INTEGER NOT NULL,
  METRIC INTEGER NOT NULL
);
INSERT INTO VW_JOIN_SCAN_A (ID, GRP, PAYLOAD) VALUES (1, 1, 'a1');
INSERT INTO VW_JOIN_SCAN_A (ID, GRP, PAYLOAD) VALUES (2, 1, 'a2');
INSERT INTO VW_JOIN_SCAN_A (ID, GRP, PAYLOAD) VALUES (3, 2, 'a3');
INSERT INTO VW_JOIN_SCAN_A (ID, GRP, PAYLOAD) VALUES (4, 2, 'a4');
INSERT INTO VW_JOIN_SCAN_B (ID, A_ID, METRIC) VALUES (1, 1, 11);
INSERT INTO VW_JOIN_SCAN_B (ID, A_ID, METRIC) VALUES (2, 1, 13);
INSERT INTO VW_JOIN_SCAN_B (ID, A_ID, METRIC) VALUES (3, 2, 17);
INSERT INTO VW_JOIN_SCAN_B (ID, A_ID, METRIC) VALUES (4, 3, 19);
INSERT INTO VW_JOIN_SCAN_B (ID, A_ID, METRIC) VALUES (5, 4, 23);
COMMIT;
