RECREATE TABLE VW_POINT_SELECT_INDEX (
  ID INTEGER NOT NULL PRIMARY KEY,
  K INTEGER NOT NULL,
  PAYLOAD VARCHAR(32)
);
CREATE INDEX IDX_VW_POINT_SELECT_INDEX_K ON VW_POINT_SELECT_INDEX (K);
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (1, 10, 'a');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (2, 20, 'b');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (3, 30, 'c');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (4, 40, 'd');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (5, 10, 'e');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (6, 20, 'f');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (7, 30, 'g');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (8, 40, 'h');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (9, 10, 'i');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (10, 20, 'j');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (11, 30, 'k');
INSERT INTO VW_POINT_SELECT_INDEX (ID, K, PAYLOAD) VALUES (12, 40, 'l');
COMMIT;
