RECREATE TABLE VW_UPDATE_HOTSET (
  ID INTEGER NOT NULL PRIMARY KEY,
  SCORE INTEGER NOT NULL
);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (1, 10);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (2, 20);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (3, 30);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (4, 40);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (5, 50);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (6, 60);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (7, 70);
INSERT INTO VW_UPDATE_HOTSET (ID, SCORE) VALUES (8, 80);
COMMIT;
