INSERT INTO VT_DDL_CREATE_TABLE_BASIC (ID, AMOUNT, NOTE) VALUES (1, 10, 'a');
INSERT INTO VT_DDL_CREATE_TABLE_BASIC (ID, AMOUNT, NOTE) VALUES (2, 20, 'b');
INSERT INTO VT_DDL_CREATE_TABLE_BASIC (ID, AMOUNT, NOTE) VALUES (3, 30, 'c');
SELECT 'ASSERT|ddl_create_table_basic.rows|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_DDL_CREATE_TABLE_BASIC;
SELECT 'ASSERT|ddl_create_table_basic.sum_amount|' || CAST(COALESCE(SUM(AMOUNT), 0) AS VARCHAR(20)) FROM VT_DDL_CREATE_TABLE_BASIC;
COMMIT;
