RECREATE TABLE VT_DML_UPDATE_DELETE (
  ID INTEGER NOT NULL PRIMARY KEY,
  SCORE INTEGER NOT NULL,
  FLAG INTEGER NOT NULL
);
INSERT INTO VT_DML_UPDATE_DELETE (ID, SCORE, FLAG) VALUES (1, 10, 0);
INSERT INTO VT_DML_UPDATE_DELETE (ID, SCORE, FLAG) VALUES (2, 20, 0);
INSERT INTO VT_DML_UPDATE_DELETE (ID, SCORE, FLAG) VALUES (3, 30, 1);
INSERT INTO VT_DML_UPDATE_DELETE (ID, SCORE, FLAG) VALUES (4, 40, 1);
COMMIT;
