INSERT INTO VT_DML_INSERT_MULTIROW (ID, GRP, PAYLOAD) VALUES (1, 1, 'r1');
INSERT INTO VT_DML_INSERT_MULTIROW (ID, GRP, PAYLOAD) VALUES (2, 1, 'r2');
INSERT INTO VT_DML_INSERT_MULTIROW (ID, GRP, PAYLOAD) VALUES (3, 2, 'r3');
INSERT INTO VT_DML_INSERT_MULTIROW (ID, GRP, PAYLOAD) VALUES (4, 2, 'r4');
SELECT 'ASSERT|dml_insert_multirow.rows|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_DML_INSERT_MULTIROW;
SELECT 'ASSERT|dml_insert_multirow.grp2|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_DML_INSERT_MULTIROW WHERE GRP = 2;
COMMIT;
