SELECT 'ASSERT|dml_join_aggregate.join_rows|' || CAST(COUNT(*) AS VARCHAR(20))
FROM VT_DML_JOIN_PARENT P
JOIN VT_DML_JOIN_CHILD C ON C.PARENT_ID = P.ID;
SELECT 'ASSERT|dml_join_aggregate.sum_metric|' || CAST(COALESCE(SUM(C.METRIC), 0) AS VARCHAR(20))
FROM VT_DML_JOIN_PARENT P
JOIN VT_DML_JOIN_CHILD C ON C.PARENT_ID = P.ID;
COMMIT;
