RECREATE TABLE VT_DML_JOIN_PARENT (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(64)
);
RECREATE TABLE VT_DML_JOIN_CHILD (
  ID INTEGER NOT NULL PRIMARY KEY,
  PARENT_ID INTEGER NOT NULL,
  METRIC INTEGER NOT NULL
);
INSERT INTO VT_DML_JOIN_PARENT (ID, NAME) VALUES (1, 'p1');
INSERT INTO VT_DML_JOIN_PARENT (ID, NAME) VALUES (2, 'p2');
INSERT INTO VT_DML_JOIN_CHILD (ID, PARENT_ID, METRIC) VALUES (1, 1, 5);
INSERT INTO VT_DML_JOIN_CHILD (ID, PARENT_ID, METRIC) VALUES (2, 1, 7);
INSERT INTO VT_DML_JOIN_CHILD (ID, PARENT_ID, METRIC) VALUES (3, 2, 11);
COMMIT;
