UPDATE VT_DML_UPDATE_DELETE SET SCORE = SCORE + 5 WHERE FLAG = 1;
DELETE FROM VT_DML_UPDATE_DELETE WHERE ID = 2;
SELECT 'ASSERT|dml_update_delete.rows|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_DML_UPDATE_DELETE;
SELECT 'ASSERT|dml_update_delete.sum_score|' || CAST(COALESCE(SUM(SCORE), 0) AS VARCHAR(20)) FROM VT_DML_UPDATE_DELETE;
COMMIT;
