RECREATE TABLE VT_INDEX_LOOKUP_PREDICATES (
  ID INTEGER NOT NULL PRIMARY KEY,
  K INTEGER NOT NULL,
  PAYLOAD VARCHAR(64)
);
CREATE INDEX IDX_VT_INDEX_LOOKUP_PRED_K ON VT_INDEX_LOOKUP_PREDICATES (K);
INSERT INTO VT_INDEX_LOOKUP_PREDICATES (ID, K, PAYLOAD) VALUES (1, 10, 'a');
INSERT INTO VT_INDEX_LOOKUP_PREDICATES (ID, K, PAYLOAD) VALUES (2, 20, 'b');
INSERT INTO VT_INDEX_LOOKUP_PREDICATES (ID, K, PAYLOAD) VALUES (3, 20, 'c');
INSERT INTO VT_INDEX_LOOKUP_PREDICATES (ID, K, PAYLOAD) VALUES (4, 30, 'd');
COMMIT;
