SELECT 'ASSERT|index_lookup_predicates.eq|' || CAST(COUNT(*) AS VARCHAR(20))
FROM VT_INDEX_LOOKUP_PREDICATES WHERE K = 20;
SELECT 'ASSERT|index_lookup_predicates.neq|' || CAST(COUNT(*) AS VARCHAR(20))
FROM VT_INDEX_LOOKUP_PREDICATES WHERE K <> 20;
COMMIT;
