SET TRANSACTION;
INSERT INTO VT_TX_COMMIT_VISIBILITY (ID, PAYLOAD) VALUES (1, 'commit_a');
INSERT INTO VT_TX_COMMIT_VISIBILITY (ID, PAYLOAD) VALUES (2, 'commit_b');
COMMIT;
SELECT 'ASSERT|tx_commit_visibility.rows|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_TX_COMMIT_VISIBILITY;
COMMIT;
