SET TRANSACTION;
INSERT INTO VT_TX_ROLLBACK_VISIBILITY (ID, PAYLOAD) VALUES (1, 'rollback_a');
INSERT INTO VT_TX_ROLLBACK_VISIBILITY (ID, PAYLOAD) VALUES (2, 'rollback_b');
ROLLBACK;
SELECT 'ASSERT|tx_rollback_visibility.rows|' || CAST(COUNT(*) AS VARCHAR(20)) FROM VT_TX_ROLLBACK_VISIBILITY;
COMMIT;
