#ifndef SCRATCHBIRD_VERSION_H
#define SCRATCHBIRD_VERSION_H

#define SCRATCHBIRD_VERSION_MAJOR 0
#define SCRATCHBIRD_VERSION_MINOR 1
#define SCRATCHBIRD_VERSION_PATCH 0
#define SCRATCHBIRD_VERSION_SUFFIX "alpha.1.01"

#define SCRATCHBIRD_VERSION_STRING "0.1.0-alpha.1.01"

#endif // SCRATCHBIRD_VERSION_H
