SELECT COUNT(*) FROM vw_point_select_index WHERE k = 10;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 40;
SELECT COUNT(*) FROM vw_point_select_index WHERE k <> 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k >= 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k <= 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k BETWEEN 10 AND 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k IN (10, 20);
SELECT COUNT(*) FROM vw_point_select_index WHERE k IN (30, 40);
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 10;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 40;
SELECT COUNT(*) FROM vw_point_select_index WHERE k <> 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k >= 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k <= 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k BETWEEN 10 AND 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k IN (10, 20);
SELECT COUNT(*) FROM vw_point_select_index WHERE k IN (30, 40);
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 10;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 20;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 30;
SELECT COUNT(*) FROM vw_point_select_index WHERE k = 40;
