#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs/specifications/parser/v3/SBLR_V3_OPCODE_PAYLOADS.md"
OUT_CPP = ROOT / "src/sblr/v3_payload_map.generated.cpp"

map_re = re.compile(r"->\s*`(SCHEMA_[A-Z0-9_]+)`")
opcode_re = re.compile(r"`(SBLR3_[A-Z0-9_]+)`")

mappings = []
for line in SPEC.read_text().splitlines():
    schema_match = map_re.search(line)
    if not schema_match:
        continue
    schema = schema_match.group(1)
    opcodes = opcode_re.findall(line.split("->", 1)[0])
    for op in opcodes:
        mappings.append((op, schema))

# de-dup
seen = {}
for op, schema in mappings:
    if op not in seen:
        seen[op] = schema

items = sorted(seen.items())

with OUT_CPP.open("w") as f:
    f.write("// generated by gen_sblr_v3_payload_map.py\n")
    f.write("#include <unordered_map>\n")
    f.write("#include <string>\n")
    f.write("\nnamespace scratchbird::sblr::v3 {\n")
    f.write("extern const std::unordered_map<std::string, std::string> kOpcodeSchemaMapGenerated = {\n")
    for op, schema in items:
        f.write(f"    {{\"{op}\", \"{schema}\"}},\n")
    f.write("};\n}\n")

print(f"Generated {OUT_CPP} with {len(items)} mappings")
