#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "docs/specifications/parser/v3/SBLR_V3_OPCODE_PAYLOADS.md"
OUT_CPP = ROOT / "src/sblr/v3_schema.generated.cpp"

schema_blocks = {}

lines = SPEC.read_text().splitlines()

codeblock_re = re.compile(r"^```")
field_re = re.compile(r"\[([^\]]+)\]")


def parse_fields(block_lines):
    fields = []
    for line in block_lines:
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        m = field_re.search(line)
        if not m:
            continue
        content = m.group(1).strip()
        if ":" not in content:
            continue
        name, typ = content.split(":", 1)
        fields.append((name.strip(), typ.strip()))
    return fields


pending_name = None

def expand_schema_names(name: str):
    if " / " not in name:
        return [name]
    parts = [p.strip() for p in name.split("/")]
    if not parts:
        return [name]
    base = parts[0]
    names = [base]
    if base.startswith("SCHEMA_") and "_" in base:
        prefix = base[: base.rfind("_") + 1]
    else:
        prefix = ""
    for part in parts[1:]:
        if part.startswith("SCHEMA_"):
            names.append(part)
        elif prefix:
            names.append(prefix + part)
        else:
            names.append(part)
    return names


i = 0
while i < len(lines):
    line = lines[i].strip()
    if line.startswith("### "):
        pending_name = line[4:].strip()
    elif line.startswith("`SCHEMA_") and line.endswith("`"):
        pending_name = line.strip("`")

    if codeblock_re.match(line):
        if pending_name:
            i += 1
            block = []
            while i < len(lines) and not codeblock_re.match(lines[i].strip()):
                block.append(lines[i])
                i += 1
            fields = parse_fields(block)
            if fields:
                for name in expand_schema_names(pending_name):
                    schema_blocks[name] = fields
            pending_name = None
        else:
            # skip block without a named schema
            i += 1
            while i < len(lines) and not codeblock_re.match(lines[i].strip()):
                i += 1
    i += 1


def map_type(typ):
    t = typ
    # normalize
    t = t.replace(" ", "")
    # list/opt
    if t.startswith("list<") and t.endswith(">"):
        return ("LIST", t[5:-1])
    if t.startswith("opt<") and t.endswith(">"):
        return ("OPT", t[4:-1])
    if t == "schema_path":
        return ("SCHEMA_PATH", "")
    if t in ("ident", "string"):
        return ("IDENT" if t == "ident" else "STRING", "")
    if t == "bytes":
        return ("BYTES", "")
    if t == "expr":
        return ("EXPR", "")
    if t == "stmt":
        return ("STMT", "")
    if t == "expr_list":
        return ("EXPR_LIST", "")
    if t == "stmt_list":
        return ("STMT_LIST", "")
    if t == "TYPE_SPEC":
        return ("TYPE_SPEC", "")
    # primitives
    prim = {
        "u8": "U8",
        "u16": "U16",
        "u32": "U32",
        "u64": "U64",
        "i8": "I8",
        "i16": "I16",
        "i32": "I32",
        "i64": "I64",
        "u128": "U128",
        "uuid": "UUID",
        "f32": "F32",
        "f64": "F64",
        "bool": "BOOL",
        "varuint": "VARUINT",
    }
    if t in prim:
        return (prim[t], "")
    # schema reference
    return ("SCHEMA", t)


with OUT_CPP.open("w") as f:
    f.write("// generated by gen_sblr_v3_schema.py\n")
    f.write("#include <unordered_map>\n")
    f.write("#include \"scratchbird/sblr/v3_schema.h\"\n\n")
    f.write("namespace scratchbird::sblr::v3 {\n")
    f.write("static const std::unordered_map<std::string, SchemaDef> kSchemas = {\n")
    for name, fields in schema_blocks.items():
        f.write(f"    {{\"{name}\", SchemaDef{{\"{name}\", {{\n")
        for fname, ftype in fields:
            kind, ref = map_type(ftype)
            f.write(f"        FieldDef{{\"{fname}\", FieldType::{kind}, \"{ref}\"}},\n")
        f.write("    }}},\n")
    f.write("};\n\n")
    f.write("const SchemaDef* lookupSchemaGenerated(std::string_view name) {\n")
    f.write("    auto it = kSchemas.find(std::string(name));\n")
    f.write("    if (it == kSchemas.end()) return nullptr;\n")
    f.write("    return &it->second;\n")
    f.write("}\n\n")
    f.write("}\n")

print(f"Generated {OUT_CPP} with {len(schema_blocks)} schemas")
