#!/usr/bin/env python3
"""
Generate canonical SBLR feature/opcode map from authoritative section-22 matrix.

Primary source candidates (first existing path wins):
1) ../local_work/docs/specifications/22_.../SBLR_FEATURE_TO_OPCODE_MATRIX.md
2) docs/specifications/22_.../SBLR_FEATURE_TO_OPCODE_MATRIX.md
"""

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_CANDIDATES = [
    ROOT.parent
    / "local_work/docs/specifications/22_SBLR_Canonical_Model_and_Opcodes/SBLR_FEATURE_TO_OPCODE_MATRIX.md",
    ROOT
    / "docs/specifications/22_SBLR_Canonical_Model_and_Opcodes/SBLR_FEATURE_TO_OPCODE_MATRIX.md",
]

OUT_H = ROOT / "include/scratchbird/sblr/v3_canonical_feature_map.generated.h"
OUT_CPP = ROOT / "src/sblr/v3_canonical_feature_map.generated.cpp"

# | `F_DML_SELECT` | `FG_DML_SQL` | `OP_STMT_DML_SELECT` | `PS_DML_SELECT` | `RS_ROWSET` |
ROW_RE = re.compile(
    r"\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|"
)


def first_existing(paths):
    for p in paths:
        if p.exists():
            return p
    return None


def read_rows(path):
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.search(line)
        if not m:
            continue
        feature_key, ast_family, opcode_symbol, payload_schema_id, result_shape_id = m.groups()
        rows.append((feature_key, ast_family, opcode_symbol, payload_schema_id, result_shape_id))
    return rows


def emit_header():
    return """// generated by gen_sblr_v3_canonical_feature_map.py
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace scratchbird::sblr::v3 {

struct CanonicalFeatureRow {
    std::string_view feature_key;
    std::string_view ast_family;
    std::string_view opcode_symbol;
    std::string_view payload_schema_id;
    std::string_view result_shape_id;
};

const CanonicalFeatureRow* lookupCanonicalFeatureByOpcodeSymbol(std::string_view opcode_symbol);
bool isCanonicalFeatureOpcodeSymbol(std::string_view opcode_symbol);
std::size_t canonicalFeatureRowCount();

}  // namespace scratchbird::sblr::v3
"""


def emit_cpp(rows):
    lines = []
    lines.append("// generated by gen_sblr_v3_canonical_feature_map.py")
    lines.append('#include "scratchbird/sblr/v3_canonical_feature_map.generated.h"')
    lines.append("")
    lines.append("namespace scratchbird::sblr::v3 {")
    lines.append("")
    lines.append("namespace {")
    lines.append("static constexpr CanonicalFeatureRow kCanonicalRows[] = {")
    for feature_key, ast_family, opcode_symbol, payload_schema_id, result_shape_id in rows:
        lines.append(
            '    {"%s", "%s", "%s", "%s", "%s"},'
            % (feature_key, ast_family, opcode_symbol, payload_schema_id, result_shape_id)
        )
    lines.append("};")
    lines.append("}  // namespace")
    lines.append("")
    lines.append(
        "const CanonicalFeatureRow* lookupCanonicalFeatureByOpcodeSymbol(std::string_view opcode_symbol) {"
    )
    lines.append("    for (const auto& row : kCanonicalRows) {")
    lines.append("        if (row.opcode_symbol == opcode_symbol) {")
    lines.append("            return &row;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("bool isCanonicalFeatureOpcodeSymbol(std::string_view opcode_symbol) {")
    lines.append("    return lookupCanonicalFeatureByOpcodeSymbol(opcode_symbol) != nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("std::size_t canonicalFeatureRowCount() {")
    lines.append("    return sizeof(kCanonicalRows) / sizeof(kCanonicalRows[0]);")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace scratchbird::sblr::v3")
    lines.append("")
    return "\n".join(lines)


def main():
    source = first_existing(SOURCE_CANDIDATES)
    if source is None:
        print("error: could not find canonical matrix source file", file=sys.stderr)
        for candidate in SOURCE_CANDIDATES:
            print(f"  - {candidate}", file=sys.stderr)
        sys.exit(1)

    rows = read_rows(source)
    if not rows:
        print(f"error: no matrix rows parsed from {source}", file=sys.stderr)
        sys.exit(2)

    OUT_H.write_text(emit_header(), encoding="utf-8")
    OUT_CPP.write_text(emit_cpp(rows), encoding="utf-8")

    print(f"Generated {OUT_H} and {OUT_CPP} with {len(rows)} canonical rows from {source}")


if __name__ == "__main__":
    main()

