#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPPING = ROOT / "docs/specifications/parser/v3/SBLR_V3_OLD_TO_NEW_MAPPING.md"
OUT_H = ROOT / "include/scratchbird/sblr/v3_opcodes.generated.h"
OUT_CPP = ROOT / "src/sblr/v3_opcodes.generated.cpp"

row_re = re.compile(r"\|\s*(0x[0-9A-Fa-f]+)\s*\|\s*(SBLR3_[A-Z0-9_]+)\s*\|")

opcodes = []
for line in MAPPING.read_text().splitlines():
    m = row_re.search(line)
    if m:
        code = int(m.group(1), 16)
        name = m.group(2)
        opcodes.append((code, name))

# de-dup by name
seen = {}
for code, name in opcodes:
    if name not in seen:
        seen[name] = code

items = sorted(seen.items(), key=lambda x: x[1])

with OUT_H.open("w") as f:
    f.write("// generated by gen_sblr_v3_opcodes.py\n")
    f.write("enum class Opcode : uint16_t {\n")
    for name, code in items:
        f.write(f"    {name} = 0x{code:04X},\n")
    f.write("};\n")

with OUT_CPP.open("w") as f:
    f.write("// generated by gen_sblr_v3_opcodes.py\n")
    f.write("#include <unordered_map>\n")
    f.write("#include \"scratchbird/sblr/v3_opcode_registry.h\"\n\n")
    f.write("namespace scratchbird::sblr::v3 {\n")
    f.write("static const std::unordered_map<uint16_t, const char*> kOpcodeNames = {\n")
    for name, code in items:
        f.write(f"    {{0x{code:04X}, \"{name}\"}},\n")
    f.write("};\n\n")
    f.write("const char* opcodeName(uint16_t opcode) {\n")
    f.write("    auto it = kOpcodeNames.find(opcode);\n")
    f.write("    return it == kOpcodeNames.end() ? nullptr : it->second;\n")
    f.write("}\n\n")
    f.write("bool isKnownOpcode(uint16_t opcode) {\n")
    f.write("    return kOpcodeNames.find(opcode) != kOpcodeNames.end();\n")
    f.write("}\n")
    f.write("}\n")

print(f"Generated {OUT_H} and {OUT_CPP} with {len(items)} opcodes")
