// generated by gen_sblr_v3_canonical_feature_map.py
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace scratchbird::sblr::v3 {

struct CanonicalFeatureRow {
    std::string_view feature_key;
    std::string_view ast_family;
    std::string_view opcode_symbol;
    std::string_view payload_schema_id;
    std::string_view result_shape_id;
};

const CanonicalFeatureRow* lookupCanonicalFeatureByOpcodeSymbol(std::string_view opcode_symbol);
bool isCanonicalFeatureOpcodeSymbol(std::string_view opcode_symbol);
std::size_t canonicalFeatureRowCount();

}  // namespace scratchbird::sblr::v3
