if(EXISTS "/home/dcalford/CliWork/ScratchBird/build_asan/tests/scratchbird_tests[1]_tests.cmake")
  include("/home/dcalford/CliWork/ScratchBird/build_asan/tests/scratchbird_tests[1]_tests.cmake")
else()
  add_test(scratchbird_tests_NOT_BUILT scratchbird_tests_NOT_BUILT)
endif()
