/*
  FILE GENERATED BY src/misc/writeBuildNum.sh
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT src/misc/writeBuildNum.sh
  FORMAL BUILD NUMBER:1
*/

#define PRODUCT_VER_STRING "0.5.0.1"
#define FILE_VER_STRING "SB-T0.5.0.1"
#define LICENSE_VER_STRING "SB-T0.5.0.1"
#define FILE_VER_NUMBER 0, 5, 0, 1
#define FB_MAJOR_VER "0"
#define FB_MINOR_VER "5"
#define FB_REV_NO "0"
#define FB_BUILD_NO "1"
#define FB_BUILD_TYPE "T"
#define FB_BUILD_SUFFIX "ScratchBird 0.5 f90eae0"
